# Generated by Django 6.0.6 on 2026-06-23 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('epoque', models.CharField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('epoque', models.CharField()),
                ('Description', models.TextField()),
                ('civilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civis.civilisation')),
            ],
        ),
    ]
