# Generated by Django 6.0.6 on 2026-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
